### ISSUE TITLE
Starting E-commerce-LykDat-Clone

### ISSUE THREAD

**Issue by Stanwukong** [Stanwukong/ecomm-lykdat-clone#1]
#### Description
E-commerce website clone built as personal project, featuring modern design, easy navigation and essential features for online sales.

#### Screenshots
![Home Page](https://i.ibb.co/f2RXz7W/Screenshot-2023-01-24-114616.jpg)
![Explore Page](https://i.ibb.co/ZWN9tkQ/explore.jpg)

#### Additional Info
- The website searches for and returns a match for clothing items matching user request.
- Project Initiated with Next.js
- Dependencies: TypeScript, ESLint, Material UI...

#### Tasks
- [ ] Draw basic structure of pages/components
- [ ] Expand with hooks
- [ ] To be determined
